/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.teldel.switcher;

public final class R {
  public static final class drawable {
    public static final int ic_minimal=0x7f010000;
    public static final int ic_stock=0x7f010001;
  }
  public static final class string {
    public static final int app_name=0x7f020000;
    public static final int switch_to_minimal=0x7f020001;
    public static final int switch_to_stock=0x7f020002;
  }
}